name: Validate Python e2e

on:
  push:
    branches:
      - main

jobs:
  setup-versions-from-manifest:
    name: Setup ${{ matrix.python }} ${{ matrix.os }}
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python: [ 3.9.13]
        exclude:

          - os: windows-latest
            python: 3.8.15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: setup-python ${{ matrix.python }}
        id: setup-python
        uses: ./
        with:
          python-version: ${{ matrix.python }}

      - name: Check python-path
        run: ./__tests__/check-python-path.sh '${{ steps.setup-python.outputs.python-path }}'
        shell: bash

      - name: Validate version
        run: |
          $pythonVersion = (python --version)
          if ("Python ${{ matrix.python }}" -ne "$pythonVersion"){
            Write-Host "The current version is $pythonVersion; expected version is ${{ matrix.python }}"
            exit 1
          }
          $pythonVersion
        shell: pwsh

      - name: Run simple code
        run: python -c 'import math; print(math.factorial(5))'
