name: Validate Python e2e

on:
  push:
    branches:
      - main

jobs:
  setup-versions-from-manifest:
    name: Setup ${{ matrix.python }} ${{ matrix.os }}
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python: [3.9.13]
        exclude:
          - os: windows-latest
            python: 3.8.15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      # Add this step to check Python version
      - name: Check Python version
        run: python --version

      - name: Change directory to repository root
        run: python ${{ github.workspace }}\app\app.py
       
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pylint
        
      - name: Running Linter
        run: |
          conda deactivate
          pylint ${{ github.workspace }}\app/*.py
        
      - name: Run unit tests
        run: |
          python ${{ github.workspace }}\tests\test_calculator.py
