name: Python CI

on: push

jobs:
  build:



    runs-on: self-hosted
    strategy:
      matrix:
        python-version: [3.9, 3.10]  # List the Python versions you want to install

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64  # Specify the architecture if needed

        

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pylint
        
    - name: Running Linter
      run: |
        pylint app/*.py
        
    - name: Run unit tests
      run: |
        python tests/test_calculator.py
