name: Validate Python e2e

on:
  push:
    branches:
      - main

jobs:
  setup-versions-from-manifest:
    name: Setup ${{ matrix.python }} ${{ matrix.os }}
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python: [ 3.9.13]
        exclude:

          - os: windows-latest
            python: 3.8.15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

